name: CD

on:
  push:
    branches:
    - "!*"
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: npm

    - run: npm ci
    - run: npm run compile
    - run: npm test
      env:
        CI: true
    - run: npm config set "//registry.npmjs.org/:_authToken" "${{ secrets.NPM_TOKEN }}"
    - run: npm publish
