name: Docs

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docs
        run: npm ci && npm run build-docs

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  docs-deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    needs:
      - build
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
